/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InputEntry: typeof import('./components/InputEntry.vue')['default'];
    Logos: typeof import('./components/Logos.vue')['default'];
    VinButton: typeof import('@vingogo/uni-ui/lib/components/button/index.vue')['default'];
    VinIcon: typeof import('@vingogo/uni-ui/lib/components/icon/index.vue')['default'];
    VinInput: typeof import('@vingogo/uni-ui/lib/components/input/index.vue')['default'];
  }
}
